### ISSUE TITLE
Cool idea

### ISSUE THREAD

**Issue by CleverSource** [jbmunsell/foooot#3]
Looks like a cool project you have coming along here. Is this going to be fully open source aka the .rbxl? I assume not since most developers take pride in it and would rather not give away something like that.

**Comment by jbmunsell** [comment]
This will be fully open sourced! I'll attach the entire project folder (including the .rbxl) as a release once it's finished. V1 will be offline play only, V2 will have gamepad support, and V3 will have online play.
